spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/kised
    username: 'root'
    password: 'rkddusgh12'
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    defer-datasource-initialization: true

logging:
  level:
    root: info
    org:
      springframework:
        security: DEBUG

services:
  service_1:
    url: 'http://localhost:8081/service1'
  service_2:
    url: 'http://localhost:8090/service2'
  urls:
    kstup: 'http://localhost:8090/service2'
    kisedorkr: 'http://localhost:8090/service2'
    startbiz: 'http://localhost:8090/service2'
    cert: 'http://localhost:8090/service2'